export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as ProductDetails} from './ProductDetails'
export {default as Puchases} from './Puchases'
export {default as CreateUser} from './CreateUser'